<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'c60d6dacecf371342c4e9cab1d0a9230',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/waterworks?serverVersion=8&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'ASSETS_VERSION' => '1.0.0',
  'WKHTMLTOPDF_PATH' => 'C:/projects/waterworks/wkhtmltopdf/bin/wkhtmltopdf',
  'WKHTMLTOIMAGE_PATH' => 'C:/projects/waterworks/wkhtmltopdf/bin/wkhtmltoimage',
);
