<?php

namespace App\Repository;

use App\Entity\ClientMeterEntity;

/**
 * ClientMeterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientMeterRepository extends \Doctrine\ORM\EntityRepository
{

    public function validate($clientMeter_form) {

        $errors = array();

        $action = $clientMeter_form['action'];

        // d = delete
        if($action !== 'd') {

            $clientMeterExist = $this->getEntityManager()->getRepository(ClientMeterEntity::class)
                ->createQueryBuilder('cm')
                ->where('cm.id != :id')
                ->andWhere('cm.meterSerialNo = :meterSerialNo')
                ->setParameters(array(
                    'meterSerialNo' => $clientMeter_form['meterSerialNo'],
                    'id' => $clientMeter_form['id']
                ))
                ->getQuery()->getResult();

            if($clientMeterExist) {
                $errors[] = 'Meter Serial No. already exist.';
            }

            if(empty($clientMeter_form['meterSerialNo'])) {
                $errors[] = 'Serial No. should not be blank.';
            }

            if(empty($clientMeter_form['presentReading'])) {
                $errors[] = 'Present Reading  should not be blank.';
            }
            
        }

        return $errors;
    }

    public function ajax_list(array $get, $userData){

        $columns = array(
            array('cm.`meter_serial_no`', 'cm.`meter_serial_no`', 'meterSerialNo'),
            array('cm.`status`', 'cm.`status`', 'status'),
            array('cm.`id`', "cm.`id`")
        );
        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `client_meter` cm";
        $sqlWhere = " WHERE cm.`is_deleted` = 0";
        $joins = "";
        $groupBy = "";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }


        if($userData['type'] != 'Super Admin' || $get['clientId']){

            $sqlWhere .= " AND cm.`client_id` = :clientId";
            $stmtParams['clientId'] = base64_decode($get['clientId']);
        }

        /*
         * Ordering
         */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        $hasUpdate = false;
        $hasDetails = false;

        
        if($userData['type'] == 'Super Admin'  || in_array('Client Details Meter Update', $userData['accesses'])){
            $hasUpdate = true;
        }

        if($userData['type'] == 'Super Admin'  || in_array('Client Details Meter Details', $userData['accesses'])){
            $hasDetails = true;
            $detailsUrl = $url . 'client_meter/details';  


        }


        foreach($result as $row) {

            $id = base64_encode($row['id']);

            $action = $hasUpdate ? "<a class='action-button-style btn btn-primary  href-modal' href='javascript:void(0)' data-id='".$id."' data-action='u'>Update</a>" : "";
            $details = $hasDetails ? "<a class='action-button-style ' href='$detailsUrl/$id'>". $row['meterSerialNo']."</a>" : $row['meterSerialNo'];

            $values = array(
                $details,
                $row['status'],
                $action
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }

    public function ajax_for_reading_list(array $get, $userData){

        $columns = array(
            array("CONCAT(c.`first_name`, ' ', IFNULL(c.`last_name`, ' '))", "CONCAT(c.`first_name`, ' ', IFNULL(c.`last_name`, ' '))", 'fullName'),
            array('p.`description`', 'p.`description`', 'purok'),
            array('cm.`meter_serial_no`', 'cm.`meter_serial_no`', 'serialNo'),
            array('DATE_FORMAT(cmr.readingDate, "%m/%d/%Y")', 'DATE_FORMAT(cmr.readingDate, "%m/%d/%Y")', 'readingDate'),
            array('cm.`present_reading`', 'cm.`present_reading`', 'presentReading'),
            array('cm.`id`', "cm.`id`")
        );
        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `client_meter` cm";
        $sqlWhere = " WHERE cm.`is_deleted` = 0";
        $sqlWhere .= " AND cm.`status` = 'Active' AND c.`is_deleted` = 0";
        $joins = " LEFT JOIN `purok` p ON p.`id` = cm.`purok_id`";
        $joins .= " LEFT JOIN `client` c ON c.`id` = cm.`client_id`";
        $joins .= " LEFT JOIN (
            SELECT 
                cmr.`status` AS status,
                cmr.`previous_reading` AS previousReading,
                cmr.`present_reading` AS presentReading,
                cmr.`consume` AS consume,
                cmr.`reading_date` AS readingDate,
                cmr.`due_date` AS dueDate,
                cmr.`billed_amount` AS billedAmt, 
                cmr.`id` AS cmrId,
                cmr.`client_meter_id` AS clientMeterId
            FROM `client_meter_reading` cmr
            WHERE cmr.`reading_date` IN (
                SELECT 
                    MAX(reading_date)
                FROM `client_meter_reading` s
                WHERE s.`is_deleted` = 0
                AND s.`client_meter_id` = cmr.`client_meter_id`
                GROUP BY s.`client_meter_id` 
            )
            AND cmr.`is_deleted` = 0
            GROUP BY cmr.`client_meter_id`  
        ) cmr ON  cm.`id` = cmr.clientMeterId ";
        $groupBy = "";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }


        if($userData['type'] != 'Super Admin' || $userData['branchId']){

            $sqlWhere .= " AND c.`branch_id` = :branchId";
            $stmtParams['branchId'] = base64_decode($userData['branchId']);
        }

        if($get['purok'] &&  $get['purok'] != 'All' ){

            $sqlWhere .= " AND p.`id` = :purokId";
            $stmtParams['purokId'] = base64_decode($get['purok']);
        }

        /*
         * Ordering
         */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";

        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        $hasReadingNew = false;

        
        if($userData['type'] == 'Super Admin'  || in_array('Dashboard Reading New', $userData['accesses'])){
            $hasReadingNew = true;
        }


        foreach($result as $row) {

            $id = base64_encode($row['id']);

            $action = $hasReadingNew ? "<a class='action-button-style btn btn-primary  href-modal' href='javascript:void(0)' data-id='0' data-meterId='".$id."' data-action='n'>Reading</a>" : "";

            $values = array(
                $row['fullName'],
                $row['purok'],
                $row['serialNo'],
                $row['readingDate'],
                $row['presentReading'],
                $action
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }

    public function ajax_pending_payment_list(array $get, $userData){

        $columns = array(
            array('c.`first_name`', "CONCAT(c.`first_name`, ' ', c.`last_name`)", 'fullName'),
            array('p.`description`', 'p.`description`', 'purok'),
            array('cm.`meter_serial_no`', 'cm.`meter_serial_no`', 'serialNo'),
            array('cmr.previousReading', 'cmr.previousReading', 'previousReading'),
            array('cmr.presentReading', 'cmr.presentReading', 'presentReading'),
            array('cmr.consume', 'cmr.consume', 'consume'),
            array('DATE_FORMAT(cmr.readingDate, "%m/%d/%Y")', 'DATE_FORMAT(cmr.readingDate, "%m/%d/%Y")', 'readingDate'),
            array('DATE_FORMAT(cmr.dueDate, "%m/%d/%Y")', 'DATE_FORMAT(cmr.dueDate, "%m/%d/%Y")', 'dueDate'),
            array('cm.`remaining_balance`', 'cm.`remaining_balance`', 'remainingBalance'),
            array('cmr.billedAmt', 'cmr.billedAmt', 'billedAmount'),
            array('cm.`id`', "cm.`id`")
        );
        $asColumns = array();

        $select = "SELECT ";
        $from = "FROM `client_meter` cm";
        $sqlWhere = " WHERE cm.`is_deleted` = 0";
        $sqlWhere .= " AND cm.`status` = 'Active' AND cmr.cmrId IS NOT NULL AND c.`is_deleted`=0";
        $joins = " LEFT JOIN `client` c ON c.`id` = cm.`client_id`";
        $joins .= " LEFT JOIN `purok` p ON p.`id` = cm.`purok_id`";
        $joins .= " LEFT JOIN (
            SELECT 
                cmr.`status` AS status,
                cmr.`previous_reading` AS previousReading,
                cmr.`present_reading` AS presentReading,
                cmr.`consume` AS consume,
                cmr.`reading_date` AS readingDate,
                cmr.`due_date` AS dueDate,
                cmr.`billed_amount` AS billedAmt, 
                cmr.`id` AS cmrId,
                cmr.`client_meter_id` AS clientMeterId
            FROM `client_meter_reading` cmr
            WHERE cmr.`status` = 'Pending Payment'
            AND cmr.`reading_date` IN (
                SELECT 
                    MAX(s.`reading_date`)
                FROM `client_meter_reading` s
                WHERE s.`status` = 'Pending Payment'
                AND s.`is_deleted` = 0
                AND s.`client_meter_id` = cmr.`client_meter_id`
                GROUP BY s.`client_meter_id` 
            )
            AND cmr.`is_deleted` = 0
            GROUP BY cmr.`client_meter_id`  
        ) cmr ON  cm.`id` = cmr.clientMeterId ";
         
        

        $groupBy = " ";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }


        if($userData['type'] != 'Super Admin' || $userData['branchId']){

            $sqlWhere .= " AND c.`branch_id` = :branchId";
            $stmtParams['branchId'] = base64_decode($userData['branchId']);
        }

        if($get['purok'] &&  $get['purok'] != 'All' ){

            $sqlWhere .= " AND p.`id` = :purokId";
            $stmtParams['purokId'] = base64_decode($get['purok']);
        }

        /*
         * Ordering
         */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";


        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        $hasPaymentNew = false;

        
        if($userData['type'] == 'Super Admin'  || in_array('Dashboard Payment New', $userData['accesses'])){
            $hasPaymentNew = true;
        }

        foreach($result as $row) {

            $id = base64_encode($row['id']);

            $action = $hasPaymentNew ? "<a class='action-button-style btn btn-primary  href-modal' href='javascript:void(0)' data-id='0' data-meterId='".$id."' data-action='n'>Payment</a>" : "";

            $values = array(
                $row['fullName'],
                $row['purok'],
                $row['serialNo'],
                $row['previousReading'],
                $row['presentReading'],
                $row['consume'],
                $row['readingDate'],
                $row['dueDate'],
                $row['remainingBalance'],
                $row['billedAmount'],
                $action
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }

    public function autocompleteSuggestions($q, $userData) {

        $stmtParams = array(
            'q' => "%" . $q['query'] . "%"
        );
        $andWhere = '';

        if($userData['type'] != 'Super Admin'){

             $andWhere.= ' WHERE u.branch_id = :branchId'; 
             $stmtParams['branchId'] = $userData['branchId'];   
        }

        
        $query = $this->getEntityManager()->getConnection()->prepare("
            SELECT
                u.`id`,
                CONCAT(u.`first_name`, ' ', u.`last_name`) AS data,
                CONCAT(u.`first_name`, ' ', u.`last_name`) AS value
            FROM `client` u
            $andWhere
            AND u.`is_deleted` != 1
            AND CONCAT(u.`first_name`, ' ', u.`last_name`) LIKE :q
            ORDER BY u.`first_name`
            LIMIT 0,20
        ");

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;
    }

    public function meter_with_pending_payment($userData, $purok){
       
        $stmtParams = array();
        $andWhere = '';

        if($userData['type'] != 'Super Admin'){
             $stmtParams['branchId'] = base64_decode($userData['branchId']);   
        }

        if($purok && $purok !=  'All'){
            $andWhere .= ' AND p.id = :purokId';
            $stmtParams['purokId'] = base64_decode($purok);  
       }

        
        $query = $this->getEntityManager()->getConnection()->prepare("
                SELECT 
                    CONCAT(c.`first_name`, ' ', c.`last_name`) AS fullName,
                    cm.`meter_serial_no` AS serialNo,
                    cmr.previousReading AS previousReading,
                    cmr.presentReading AS presentReading,
                    cmr.consume AS consume, 
                    DATE_FORMAT(cmr.readingDate, '%m/%d/%Y') AS readingDate,
                    DATE_FORMAT(cmr.dueDate, '%m/%d/%Y') AS dueDate,
                    cm.`remaining_balance` AS remainingBalance,
                    cmr.billedAmt AS billedAmount,
                    cmr.amountPerCubic AS amountPerCubic,
                    cm.`id`,
                    co.`description` AS company,
                    co.`address` AS companyAddress,
                    p.`description` AS purok,
                    DATE_FORMAT(cmc.firstPendingPayment, '%m/%d/%Y') AS firstPendingPayment  
                FROM `client_meter` cm 
                LEFT JOIN `client` c ON c.`id` = cm.`client_id` 
                LEFT JOIN `purok` p ON p.`id` = cm.`purok_id` 
                LEFT JOIN `branch` b ON b.`id` = c.`branch_id`
                LEFT JOIN `company` co ON co.`id` = b.`company_id` 
                LEFT JOIN ( 
                    SELECT 
                        cmr.`status` AS status,
                        cmr.`previous_reading` AS previousReading,
                        cmr.`present_reading` AS presentReading,
                        cmr.`consume` AS consume,
                        cmr.`reading_date` AS readingDate,
                        cmr.`due_date` AS dueDate,
                        cmr.`billed_amount` AS billedAmt,
                        cmr.`amount_per_cubic` AS amountPerCubic,
                        cmr.`id` AS cmrId, cmr.`client_meter_id` AS clientMeterId 
                    FROM `client_meter_reading` cmr 
                    WHERE cmr.`status` = 'Pending Payment' 
                    AND cmr.`reading_date` IN ( 
                        SELECT 
                            MAX(reading_date) 
                            FROM `client_meter_reading` s 
                        WHERE s.`status` = 'Pending Payment' 
                        AND s.`is_deleted` = 0 
                        GROUP BY s.`client_meter_id` ) 
                    AND cmr.`is_deleted` = 0 
                    GROUP BY cmr.`client_meter_id` ) cmr ON cm.`id` = cmr.clientMeterId 
                LEFT JOIN ( 
                    SELECT 
                        cmc.`due_date` AS firstPendingPayment,
                        cmc.`client_meter_id` AS cclientMeterId 
                    FROM `client_meter_reading` cmc 
                    WHERE cmc.`status` = 'Pending Payment' 
                    AND cmc.`reading_date` IN ( 
                        SELECT 
                            MIN(reading_date) 
                            FROM `client_meter_reading` s 
                        WHERE s.`status` = 'Pending Payment' 
                        AND s.`is_deleted` = 0 
                        GROUP BY s.`client_meter_id` ) 
                    AND cmc.`is_deleted` = 0 
                    GROUP BY cmc.`client_meter_id` ) cmc ON cm.`id` = cmc.cclientMeterId   
                WHERE cm.`is_deleted` = 0 
                AND cm.`status` = 'Active' 
                AND cmr.cmrId IS NOT NULL 
                AND c.`branch_id` = :branchId 
                AND c.`is_deleted` = 0
                ".$andWhere."
                ORDER BY cm.`purok_id` asc
        ");

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;

    }

    
    public function master_list($purok, $userData){
       
        $stmtParams = array();
        $andWhere = '';

        if($userData['type'] != 'Super Admin'){
             $stmtParams['branchId'] = base64_decode($userData['branchId']);   
        }

        if($purok && $purok !=  'All'){
            $andWhere .= ' AND p.id = :purokId';
            $stmtParams['purokId'] = base64_decode($purok);   
       }

        
        $query = $this->getEntityManager()->getConnection()->prepare('
            SELECT 
                CONCAT(c.`first_name`, " ", c.`last_name`) AS fullName,
                p.`description` AS purok,
                cm.`meter_serial_no` AS serialNo,
                DATE_FORMAT(cmr.readingDate, "%m/%d/%Y") AS readingDate,
                cm.`present_reading` AS presentReading, 
                cm.`id` 
            FROM `client_meter` cm 
            LEFT JOIN `purok` p ON p.`id` = cm.`purok_id` 
            LEFT JOIN `client` c ON c.`id` = cm.`client_id` 
            LEFT JOIN ( 
                SELECT
                     cmr.`status` AS status,
                     cmr.`previous_reading` AS previousReading, 
                     cmr.`present_reading` AS presentReading, 
                     cmr.`consume` AS consume, 
                     cmr.`reading_date` AS readingDate, 
                     cmr.`due_date` AS dueDate, 
                     cmr.`billed_amount` AS billedAmt, 
                     cmr.`id` AS cmrId, 
                     cmr.`client_meter_id` AS clientMeterId 
                FROM `client_meter_reading` cmr 
                WHERE cmr.`reading_date` IN 
                    ( 
                        SELECT 
                            MAX(reading_date) 
                        FROM `client_meter_reading` s 
                        WHERE s.`is_deleted` = 0 
                        GROUP BY s.`client_meter_id` 
                    ) 
                AND cmr.`is_deleted` = 0 
                GROUP BY cmr.`client_meter_id` 
            ) cmr ON cm.`id` = cmr.clientMeterId 
            WHERE cm.`is_deleted` = 0 
            AND cm.`status` = "Active" 
            AND c.`is_deleted` = 0 
            AND c.`branch_id` = :branchId 
            '.$andWhere.'
            ORDER BY p.`description` asc
        ');

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;

    }

   
}
